// Local reference images in public/reference folder
export const ASL_ALPHABET: Record<string, string> = {
    a: '/reference/A/250px-Sign_language_A.svg.png',
    b: '/reference/B/250px-Sign_language_B.svg.png',
    c: '/reference/C/250px-Sign_language_C.svg.png',
    d: '/reference/D/250px-Sign_language_D.svg.png',
    e: '/reference/E/250px-Sign_language_E.svg.png',
    f: '/reference/F/250px-Sign_language_F.svg.png',
    g: '/reference/G/250px-Sign_language_G.svg.png',
    h: '/reference/H/250px-Sign_language_H.svg.png',
    i: '/reference/I/250px-Sign_language_I.svg.png',
    j: '/reference/J/250px-Sign_language_J.svg.png',
    k: '/reference/K/250px-Sign_language_K.svg.png',
    l: '/reference/L/250px-Sign_language_L.svg.png',
    m: '/reference/M/250px-Sign_language_M.svg.png',
    n: '/reference/N/250px-Sign_language_N.svg.png',
    o: '/reference/O/250px-Sign_language_O.svg.png',
    p: '/reference/P/250px-Sign_language_P.svg.png',
    q: '/reference/Q/250px-Sign_language_Q.svg.png',
    r: '/reference/R/250px-Sign_language_R.svg.png',
    s: '/reference/S/250px-Sign_language_S.svg.png',
    t: '/reference/T/250px-Sign_language_T.svg.png',
    u: '/reference/U/250px-Sign_language_U.svg.png',
    v: '/reference/V/250px-Sign_language_V.svg.png',
    w: '/reference/W/250px-Sign_language_W.svg.png',
    x: '/reference/X/250px-Sign_language_X.svg.png',
    y: '/reference/Y/250px-Sign_language_Y.svg.png',
    z: '/reference/Z/250px-Sign_language_Z.svg.png',
};